spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/authdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql:  true

  application:
    name: auth-service

server:
  port: 8084
