spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: ${DB_PASSWORD}
    password: ${DB_USERNAME}
  jpa:
    hibernate:
     ddl-auto: update
    show-sql:  true

    application:
      name: auth-service

server:
  port: 8084
