version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/auth-service"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/order-service"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/payment-service"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/api-gateway"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/notification-service"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/common-events"
    schedule:
<<<<<<< HEAD
      interval: "daily"
=======
      interval: "daily"
>>>>>>> 711c9d6 (Updated microservices changes)
