spring:
  application :
    name : order-service
  datasource:
    url: jdbc:postgresql://postgres-order:5432/orderdb
    username: postgres
    password: KrishPooja@0703

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port : 8081
logging:
  file:
    name: Order-service_application.log
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder : TRACE
