spring.application.name=order-service
server.port=8081
logging.file.name=Order-service_application.log
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE